sudo: required
services:
  - docker

before_install:
  - docker build -t tranng/docker-react -f Dockerfile.dev .

script:
  - docker run tranng/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-NV"
  env: "DockerReactNv-env"
  bucket_name: "elasticbeanstalk-us-east-1-529154268433"
  bucket_path: "docker-react-NV"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"